FROM 119268833526.dkr.ecr.us-east-2.amazonaws.com/trusted360:api-clean

# Environment variables will be provided by ECS task definition
ENV NODE_ENV=development
ENV REDIS_URL=redis://localhost:6379
ENV JWT_SECRET=production-jwt-secret-key-87432
ENV SKIP_MIGRATIONS=false

CMD ["npm", "start"]
