/**
 * Migration: Create members table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('members', (table) => {
    table.uuid('id').primary();
    table.uuid('household_id').notNullable();
    table.string('name', 255).notNullable();
    table.string('email', 255);
    table.string('role', 50).defaultTo('member');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.foreign('household_id').references('id').inTable('households');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('members');
};
