/**
 * Migration: Create recipes table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('recipes', (table) => {
    table.uuid('id').primary();
    table.string('name', 255).notNullable();
    table.text('description');
    table.text('instructions');
    table.integer('prep_time');
    table.integer('cook_time');
    table.integer('servings');
    table.string('difficulty', 50);
    table.string('source_url', 512);
    table.string('image_url', 512);
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.specificType('search_vector', 'tsvector');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('recipes');
};
