/**
 * Migration: Create ingredients table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('ingredients', (table) => {
    table.uuid('id').primary();
    table.string('name', 255).notNullable();
    table.string('category', 100);
    table.string('store_section', 100);
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('ingredients');
};
