/**
 * Migration: Create shopping_list_items table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('shopping_list_items', (table) => {
    table.uuid('id').primary();
    table.uuid('shopping_list_id').notNullable();
    table.uuid('ingredient_id');
    table.string('name', 255).notNullable();
    table.decimal('quantity');
    table.string('unit', 50);
    table.string('store_section', 100);
    table.boolean('purchased').defaultTo(false);
    table.text('notes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('unit_id');
    table.uuid('tenant_id');
    table.integer('store_section_order');
    table.foreign('shopping_list_id').references('id').inTable('shopping_lists');
    table.foreign('ingredient_id').references('id').inTable('ingredients');
    table.foreign('unit_id').references('id').inTable('units');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('shopping_list_items');
};
