/**
 * Migration: Create meal_feedback table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_feedback', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_history_item_id').notNullable();
    table.uuid('member_id').notNullable();
    table.integer('rating').notNullable();
    table.text('feedback_text');
    table.boolean('consumed_all').notNullable().defaultTo(true);
    table.boolean('would_eat_again').notNullable().defaultTo(true);
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_history_item_id').references('id').inTable('meal_history_items');
    table.foreign('member_id').references('id').inTable('members');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_feedback');
};
