/**
 * Migration: Create user_sessions table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('user_sessions', (table) => {
    table.uuid('id').primary();
    table.uuid('user_id').notNullable();
    table.string('token', 255).notNullable();
    table.string('refresh_token', 255);
    table.specificType('ip_address', 'inet');
    table.text('user_agent');
    table.jsonb('device_info');
    table.timestamp('expires_at', { useTz: true }).notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('last_activity_at', { useTz: true }).defaultTo(knex.fn.now());
    table.boolean('is_active').defaultTo(true);
    table.uuid('tenant_id');
    table.foreign('user_id').references('id').inTable('users');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('user_sessions');
};
