/**
 * Migration: Create store_sections table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('store_sections', (table) => {
    table.uuid('id').primary();
    table.string('name', 100).notNullable();
    table.integer('display_order').notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('store_sections');
};
