/**
 * Migration: Create food_allergies table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('food_allergies', (table) => {
    table.uuid('id').primary();
    table.uuid('member_id').notNullable();
    table.uuid('ingredient_id').notNullable();
    table.string('severity', 50).notNullable();
    table.text('notes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('member_id').references('id').inTable('members');
    table.foreign('ingredient_id').references('id').inTable('ingredients');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('food_allergies');
};
