/**
 * Migration: Create meal_history table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_history', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_id').notNullable();
    table.uuid('household_id').notNullable();
    table.date('week_start_date').notNullable();
    table.date('week_end_date').notNullable();
    table.string('status', 20).notNullable().defaultTo('completed');
    table.integer('completion_percentage').notNullable().defaultTo(0);
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
    table.foreign('household_id').references('id').inTable('households');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_history');
};
