/**
 * Migration: Create meal_plan_approvals table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_plan_approvals', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_id').notNullable();
    table.uuid('member_id').notNullable();
    table.integer('version_number').notNullable();
    table.string('response', 20).notNullable();
    table.timestamp('response_date', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.text('feedback');
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_plan_approvals');
};
