/**
 * Migration: Create knex_migrations_lock table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('knex_migrations_lock', (table) => {
    table.increments('index');
    table.integer('is_locked');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('knex_migrations_lock');
};
