/**
 * Migration: Create meal_plan_comments table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_plan_comments', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_id').notNullable();
    table.uuid('member_id').notNullable();
    table.integer('version_number').notNullable();
    table.text('comment').notNullable();
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_plan_comments');
};
