/**
 * Migration: Create units table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('units', (table) => {
    table.uuid('id').primary();
    table.string('name', 50).notNullable();
    table.string('symbol', 10).notNullable();
    table.string('category', 50).notNullable();
    table.uuid('base_unit_id');
    table.decimal('conversion_factor');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('base_unit_id').references('id').inTable('units');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('units');
};
