/**
 * Migration: Create knex_migrations table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('knex_migrations', (table) => {
    table.increments('id');
    table.string('name', 255);
    table.integer('batch');
    table.timestamp('migration_time', { useTz: true });
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('knex_migrations');
};
