/**
 * Migration: Create notification_recipients table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('notification_recipients', (table) => {
    table.uuid('id').primary();
    table.uuid('notification_id').notNullable();
    table.string('recipient_type', 20).notNullable();
    table.uuid('recipient_id').notNullable();
    table.string('status', 20).notNullable().defaultTo('pending');
    table.timestamp('read_at', { useTz: false });
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('notification_id').references('id').inTable('notifications');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('notification_recipients');
};
