/**
 * Migration: Create categories table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('categories', (table) => {
    table.uuid('id').primary();
    table.string('name', 100).notNullable();
    table.text('description');
    table.uuid('category_group_id');
    table.uuid('parent_id');
    table.integer('display_order').notNullable().defaultTo(0);
    table.string('icon', 100);
    table.string('color', 20);
    table.boolean('is_default').notNullable().defaultTo(false);
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('category_group_id').references('id').inTable('category_groups');
    table.foreign('parent_id').references('id').inTable('categories');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('categories');
};
