/**
 * Migration: Create recipe_categories table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('recipe_categories', (table) => {
    table.uuid('id').primary();
    table.uuid('recipe_id').notNullable();
    table.uuid('category_id').notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('recipe_id').references('id').inTable('recipes');
    table.foreign('category_id').references('id').inTable('categories');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('recipe_categories');
};
