/**
 * Migration: Create recipe_tags table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('recipe_tags', (table) => {
    table.uuid('id').primary();
    table.uuid('recipe_id').notNullable();
    table.string('tag', 100).notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.foreign('recipe_id').references('id').inTable('recipes');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('recipe_tags');
};
