/**
 * Migration: Create meal_plan_versions table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_plan_versions', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_id').notNullable();
    table.integer('version_number').notNullable();
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('created_by');
    table.string('status', 20).notNullable().defaultTo('draft');
    table.jsonb('data').notNullable();
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_plan_versions');
};
