/**
 * Migration: Create dietary_preferences table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('dietary_preferences', (table) => {
    table.uuid('id').primary();
    table.uuid('member_id').notNullable();
    table.string('preference_type', 50).notNullable();
    table.string('preference_value', 255).notNullable();
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.foreign('member_id').references('id').inTable('members');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('dietary_preferences');
};
