/**
 * Migration: Create member_diets table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('member_diets', (table) => {
    table.uuid('id').primary();
    table.uuid('member_id').notNullable();
    table.uuid('diet_type_id').notNullable();
    table.date('starts_on').notNullable();
    table.date('ends_on');
    table.text('notes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('member_id').references('id').inTable('members');
    table.foreign('diet_type_id').references('id').inTable('diet_types');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('member_diets');
};
