/**
 * Migration: Create category_groups table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('category_groups', (table) => {
    table.uuid('id').primary();
    table.string('name', 100).notNullable();
    table.text('description');
    table.integer('display_order').notNullable().defaultTo(0);
    table.string('icon', 100);
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('category_groups');
};
