/**
 * Migration: Create meal_plan_items table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_plan_items', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_id').notNullable();
    table.uuid('recipe_id').notNullable();
    table.date('planned_date').notNullable();
    table.string('meal_type', 50).notNullable();
    table.integer('servings').notNullable().defaultTo(1);
    table.text('notes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
    table.foreign('recipe_id').references('id').inTable('recipes');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_plan_items');
};
