/**
 * Migration: Create recipe_ingredients table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('recipe_ingredients', (table) => {
    table.uuid('id').primary();
    table.uuid('recipe_id').notNullable();
    table.uuid('ingredient_id').notNullable();
    table.decimal('quantity');
    table.string('unit', 50);
    table.text('notes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('unit_id');
    table.uuid('tenant_id');
    table.foreign('recipe_id').references('id').inTable('recipes');
    table.foreign('ingredient_id').references('id').inTable('ingredients');
    table.foreign('unit_id').references('id').inTable('units');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('recipe_ingredients');
};
