/**
 * Migration: Create two_factor_auth table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('two_factor_auth', (table) => {
    table.uuid('id').primary();
    table.uuid('user_id').notNullable();
    table.string('secret', 255).notNullable();
    table.boolean('is_enabled').defaultTo(false);
    table.jsonb('backup_codes');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('user_id').references('id').inTable('users');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('two_factor_auth');
};
