/**
 * Migration: Create meal_history_items table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_history_items', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_history_id').notNullable();
    table.uuid('meal_plan_item_id').notNullable();
    table.uuid('recipe_id').notNullable();
    table.date('planned_date').notNullable();
    table.date('actual_date');
    table.string('meal_type', 20).notNullable();
    table.boolean('was_prepared').notNullable().defaultTo(false);
    table.boolean('was_substituted').notNullable().defaultTo(false);
    table.uuid('substituted_recipe_id');
    table.integer('servings').notNullable();
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_history_id').references('id').inTable('meal_history');
    table.foreign('recipe_id').references('id').inTable('recipes');
    table.foreign('substituted_recipe_id').references('id').inTable('recipes');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_history_items');
};
