/**
 * Migration: Create meal_plan_item_approvals table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_plan_item_approvals', (table) => {
    table.uuid('id').primary();
    table.uuid('meal_plan_approval_id').notNullable();
    table.uuid('meal_plan_item_id').notNullable();
    table.string('response', 20).notNullable();
    table.uuid('suggested_recipe_id');
    table.text('feedback');
    table.uuid('tenant_id').notNullable();
    table.foreign('meal_plan_approval_id').references('id').inTable('meal_plan_approvals');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_plan_item_approvals');
};
