/**
 * Migration: Create category_rules table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('category_rules', (table) => {
    table.uuid('id').primary();
    table.uuid('category_id').notNullable();
    table.string('rule_type').notNullable();
    table.jsonb('rule_value').notNullable();
    table.integer('priority').notNullable().defaultTo(0);
    table.jsonb('conditions');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.uuid('tenant_id');
    table.foreign('category_id').references('id').inTable('categories');
    table.foreign('tenant_id').references('id').inTable('tenants');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('category_rules');
};
