/**
 * Migration: Create shopping_lists table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('shopping_lists', (table) => {
    table.uuid('id').primary();
    table.uuid('household_id').notNullable();
    table.uuid('meal_plan_id');
    table.string('name', 255).notNullable();
    table.string('status', 50).defaultTo('active');
    table.timestamp('created_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: true }).defaultTo(knex.fn.now());
    table.timestamp('generated_on', { useTz: true }).defaultTo(knex.fn.now());
    table.foreign('household_id').references('id').inTable('households');
    table.foreign('meal_plan_id').references('id').inTable('meal_plans');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('shopping_lists');
};
