/**
 * Migration: Create meal_insights table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('meal_insights', (table) => {
    table.uuid('id').primary();
    table.uuid('household_id').notNullable();
    table.string('insight_type', 50).notNullable();
    table.jsonb('insight_data').notNullable();
    table.integer('confidence').notNullable();
    table.boolean('is_applied').notNullable().defaultTo(false);
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
    table.foreign('household_id').references('id').inTable('households');
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('meal_insights');
};
