/**
 * Migration: Create notification_channels table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('notification_channels', (table) => {
    table.uuid('id').primary();
    table.string('name', 50).notNullable();
    table.string('type', 20).notNullable();
    table.jsonb('config').notNullable();
    table.boolean('active').notNullable().defaultTo(true);
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('notification_channels');
};
