/**
 * Migration: Create notification_preferences table
 * Generated by simmer schema utility
 */
exports.up = function(knex) {
  return knex.schema.createTable('notification_preferences', (table) => {
    table.uuid('id').primary();
    table.string('entity_type', 20).notNullable();
    table.uuid('entity_id').notNullable();
    table.string('notification_type', 50).notNullable();
    table.jsonb('channels').notNullable();
    table.boolean('enabled').notNullable().defaultTo(true);
    table.time('quiet_hours_start', { useTz: false });
    table.time('quiet_hours_end', { useTz: false });
    table.integer('frequency_limit');
    table.timestamp('created_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.timestamp('updated_at', { useTz: false }).notNullable().defaultTo(knex.fn.now());
    table.uuid('tenant_id').notNullable();
  });
};

exports.down = function(knex) {
  return knex.schema.dropTable('notification_preferences');
};
